version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: GIFTProject
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./pg-script:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"