version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: GIFT-Project
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"